version: '3.8'

services:
  mongo_db:
    image: mongo:6
    container_name: mongodb_container
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  myapp:
    build: .
    container_name: weather_service_node
    ports:
      - "4000:3000"
    environment:
       MONGO_URI: mongodb://mongo_db:27017/weather
       POST: 3000
       WEB_SOCKET_URL: ws://host.docker.internal:8765
    depends_on:
      - mongo_db

volumes:
  mongo-data:
